In [1]:
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
import numpy as np

In [2]:
raw_data = pd.read_csv("600K US Housing Properties.csv")
raw_data.head()

C:\Users\supre\AppData\Local\Temp\ipykernel_8200\4237909321.py:1: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  raw_data = pd.read_csv("600K US Housing Properties.csv")

,property_url,property_id,address,street_name,apartment,city,state,latitude,longitude,postcode,...,property_type,property_status,year_build,total_num_units,listing_age,RunDate,agency_name,agent_name,agent_phone,is_owned_by_zillow
0,https://www.zillow.com/homedetails/3-Plat-83-1...,2064212272,"3 Plat #83-10, Wrangell, AK 99929",Plat #83-10,NaN,Wrangell,AK,NaN,NaN,99929,...,LOT,FOR_SALE,NaN,NaN,-1,2022-04-24 07:34:15,Anchor Properties,NaN,NaN,0
1,https://www.zillow.com/homedetails/117-3rd-St-...,249518113,"117 3rd St, Wrangell, AK 99929",3rd St,NaN,Wrangell,AK,56.474518,-132.38600,99929,...,SINGLE_FAMILY,FOR_SALE,NaN,NaN,-1,2022-04-24 07:34:15,NaN,NaN,NaN,0
2,https://www.zillow.com/homedetails/LOT-2A-Fron...,2077729913,"LOT 2A Front St, Wrangell, AK 99929",LOT 2A Front St,NaN,Wrangell,AK,56.471638,-132.38686,99929,...,LOT,FOR_SALE,NaN,NaN,-1,2022-04-24 07:34:15,NaN,NaN,NaN,0
3,https://www.zillow.com/homedetails/LOT-A-Plat-...,2067488502,"LOT A Plat #2009-6, Wrangell, AK 99929",LOT A Plat #2009-6,NaN,Wrangell,AK,NaN,NaN,99929,...,SINGLE_FAMILY,FOR_SALE,NaN,NaN,-1,2022-04-24 07:34:15,"Petersburg Properties, LLC",NaN,NaN,0
4,https://www.zillow.com/homedetails/335-Cassiar...,249518139,"335 Cassiar St, Wrangell, AK 99929",Cassiar St,NaN,Wrangell,AK,56.475697,-132.38905,99929,...,SINGLE_FAMILY,FOR_SALE,NaN,NaN,-1,2022-04-24 07:34:15,NaN,NaN,NaN,0

In [3]:
# Selecting usefull Columns and Dropping others
raw_data = raw_data[['property_id','address','street_name','city','state','latitude','longitude','postcode'
            ,'price','bedroom_number','bathroom_number','price_per_unit','living_space','land_space','land_space_unit'
            ,'property_type']]

In [4]:
raw_data

,property_id,address,street_name,city,state,latitude,longitude,postcode,price,bedroom_number,bathroom_number,price_per_unit,living_space,land_space,land_space_unit,property_type
0,2064212272,"3 Plat #83-10, Wrangell, AK 99929",Plat #83-10,Wrangell,AK,NaN,NaN,99929,135000.0,NaN,NaN,NaN,NaN,3.8860,acres,LOT
1,249518113,"117 3rd St, Wrangell, AK 99929",3rd St,Wrangell,AK,56.474518,-132.386000,99929,589500.0,3.0,3.0,237.0,2478.0,7492.0000,sqft,SINGLE_FAMILY
2,2077729913,"LOT 2A Front St, Wrangell, AK 99929",LOT 2A Front St,Wrangell,AK,56.471638,-132.386860,99929,99999.0,NaN,0.0,NaN,NaN,7222.0000,sqft,LOT
3,2067488502,"LOT A Plat #2009-6, Wrangell, AK 99929",LOT A Plat #2009-6,Wrangell,AK,NaN,NaN,99929,495000.0,3.0,1.0,330.0,1500.0,61.9705,acres,SINGLE_FAMILY
4,249518139,"335 Cassiar St, Wrangell, AK 99929",Cassiar St,Wrangell,AK,56.475697,-132.389050,99929,405000.0,5.0,3.0,194.0,2080.0,10436.0000,sqft,SINGLE_FAMILY
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599995,4303608,"6317 Virginia Ln, Matteson, IL 60443",Virginia Ln,Matteson,IL,41.523070,-87.769340,60443,350000.0,4.0,3.0,134.0,2600.0,10375.9920,sqft,SINGLE_FAMILY
599996,2078144422,"LOT 16 Ray Ave, West Chicago, IL 60185",LOT 16 Ray Ave,West Chicago,IL,NaN,NaN,60185,29900.0,NaN,NaN,NaN,NaN,0.2600,acres,LOT
599997,4604875,"12S135 Lemont Rd, Lemont, IL 60439",135 Lemont Rd,Lemont,IL,41.697723,-88.003746,60439,859000.0,3.0,3.0,254.0,3373.0,4.8204,acres,SINGLE_FAMILY
599998,65578365,"4701 Abbey Ln, Matteson, IL 60443",Abbey Ln,Matteson,IL,41.519527,-87.730644,60443,465000.0,5.0,4.0,140.0,3301.0,10193.0400,sqft,SINGLE_FAMILY
599999,4418670,"321 Allen Ave, West Chicago, IL 60185",Allen Ave,West Chicago,IL,41.879490,-88.203010,60185,310000.0,4.0,2.0,181.0,1709.0,6634.1880,sqft,SINGLE_FAMILY

In [5]:
raw_data.describe()

,property_id,latitude,longitude,price,bedroom_number,bathroom_number,price_per_unit,living_space,land_space
count,6.000000e+05,529122.000000,529122.000000,6.000000e+05,443845.000000,471733.000000,4.353650e+05,4.478470e+05,5.151190e+05
mean,8.885042e+08,36.282379,-105.813906,6.051870e+05,3.411964,2.471116,4.840448e+02,4.298387e+03,3.099427e+03
std,9.724708e+08,5.673355,13.464633,3.175555e+06,22.491600,5.684972,2.985527e+04,1.780201e+05,5.350082e+03
min,2.700000e+01,18.985142,-165.408250,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00,-1.306800e+04
25%,5.402143e+07,32.612112,-117.346079,1.700000e+05,3.000000,2.000000,1.550000e+02,1.360000e+03,1.010000e+00
50%,2.066090e+08,35.403568,-101.897378,3.699000e+05,3.000000,2.000000,2.200000e+02,1.863000e+03,6.000000e+01
75%,2.066867e+09,39.661674,-95.354245,6.250000e+05,4.000000,3.000000,3.310000e+02,2.574000e+03,6.534000e+03
max,2.146997e+09,71.299170,-87.525570,2.147484e+09,13210.000000,1892.000000,1.590000e+07,5.991327e+07,1.746756e+06

In [6]:
raw_data.isnull().sum()

property_id             0
address                 0
street_name           131
city                    1
state                   1
latitude            70878
longitude           70878
postcode               30
price                   0
bedroom_number     156155
bathroom_number    128267
price_per_unit     164635
living_space       152153
land_space          84881
land_space_unit     84881
property_type           0
dtype: int64

In [7]:
raw_data.dropna(subset=['price_per_unit'], inplace=True)

In [8]:
raw_data.isnull().sum()

property_id            0
address                0
street_name           10
city                   1
state                  0
latitude           28314
longitude          28314
postcode               5
price                  0
bedroom_number      5206
bathroom_number     3119
price_per_unit         0
living_space           0
land_space         76491
land_space_unit    76491
property_type          0
dtype: int64

In [9]:
raw_data.dropna(subset=['land_space'], inplace=True)

In [10]:
raw_data.isnull().sum()

property_id            0
address                0
street_name            4
city                   1
state                  0
latitude           23135
longitude          23135
postcode               5
price                  0
bedroom_number      4809
bathroom_number     2875
price_per_unit         0
living_space           0
land_space             0
land_space_unit        0
property_type          0
dtype: int64

In [11]:
raw_data.dropna(subset=['bedroom_number'], inplace=True)

In [12]:
raw_data.isnull().sum()

property_id            0
address                0
street_name            4
city                   1
state                  0
latitude           22327
longitude          22327
postcode               3
price                  0
bedroom_number         0
bathroom_number      403
price_per_unit         0
living_space           0
land_space             0
land_space_unit        0
property_type          0
dtype: int64

In [13]:
raw_data.dropna(subset=['bathroom_number'], inplace=True)

In [14]:
raw_data.isnull().sum()

property_id            0
address                0
street_name            4
city                   1
state                  0
latitude           22302
longitude          22302
postcode               3
price                  0
bedroom_number         0
bathroom_number        0
price_per_unit         0
living_space           0
land_space             0
land_space_unit        0
property_type          0
dtype: int64

In [35]:
raw_data.dropna(subset=['latitude'], inplace=True)

In [36]:
raw_data.dropna(subset=['longitude'], inplace=True)

In [38]:
raw_data.isnull().sum()

property_id        0
address            0
street_name        1
city               1
state              0
latitude           0
longitude          0
postcode           0
price              0
bedroom_number     0
bathroom_number    0
price_per_unit     0
living_space       0
land_space         0
land_space_unit    0
property_type      0
dtype: int64

In [39]:
raw_data.dropna(subset=['street_name'], inplace=True)

In [41]:
raw_data.dropna(subset=['city'], inplace=True)

In [42]:
raw_data.isnull().sum()

property_id        0
address            0
street_name        0
city               0
state              0
latitude           0
longitude          0
postcode           0
price              0
bedroom_number     0
bathroom_number    0
price_per_unit     0
living_space       0
land_space         0
land_space_unit    0
property_type      0
dtype: int64

In [43]:
raw_data

,property_id,address,street_name,city,state,latitude,longitude,postcode,price,bedroom_number,bathroom_number,price_per_unit,living_space,land_space,land_space_unit,property_type
0,249518113,"117 3rd St, Wrangell, AK 99929",3rd St,Wrangell,AK,56.474518,-132.386000,99929,589500.0,3.0,3.0,237.0,2478.0,7492.000,sqft,SINGLE_FAMILY
1,249518139,"335 Cassiar St, Wrangell, AK 99929",Cassiar St,Wrangell,AK,56.475697,-132.389050,99929,405000.0,5.0,3.0,194.0,2080.0,10436.000,sqft,SINGLE_FAMILY
3,2069574197,"532.5 Front St, Wrangell, AK 99929",5 Front St,Wrangell,AK,56.468544,-132.379650,99929,130000.0,3.0,1.0,104.0,1250.0,3483.000,sqft,SINGLE_FAMILY
5,243013558,"501 Noseeum St, Petersburg, AK 99833",Noseeum St,Petersburg,AK,56.806820,-132.961800,99833,165000.0,1.0,1.0,235.0,700.0,15367.968,sqft,SINGLE_FAMILY
7,243013641,"905 Odin St, Petersburg, AK 99833",Odin St,Petersburg,AK,56.806230,-132.971130,99833,375000.0,3.0,3.0,226.0,1652.0,8000.000,sqft,SINGLE_FAMILY
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291229,4032186,"1026 Crestview Dr, Lemont, IL 60439",Crestview Dr,Lemont,IL,41.662193,-87.993800,60439,359990.0,3.0,2.0,196.0,1832.0,11900.592,sqft,SINGLE_FAMILY
291230,83909960,"611 Hickory Ln, West Chicago, IL 60185",Hickory Ln,West Chicago,IL,41.898396,-88.192670,60185,549000.0,4.0,5.0,161.0,3409.0,10890.000,sqft,SINGLE_FAMILY
291231,4303608,"6317 Virginia Ln, Matteson, IL 60443",Virginia Ln,Matteson,IL,41.523070,-87.769340,60443,350000.0,4.0,3.0,134.0,2600.0,10375.992,sqft,SINGLE_FAMILY
291232,65578365,"4701 Abbey Ln, Matteson, IL 60443",Abbey Ln,Matteson,IL,41.519527,-87.730644,60443,465000.0,5.0,4.0,140.0,3301.0,10193.040,sqft,SINGLE_FAMILY
291233,4418670,"321 Allen Ave, West Chicago, IL 60185",Allen Ave,West Chicago,IL,41.879490,-88.203010,60185,310000.0,4.0,2.0,181.0,1709.0,6634.188,sqft,SINGLE_FAMILY

In [44]:
raw_data.dtypes

property_id          int64
address             object
street_name         object
city                object
state               object
latitude           float64
longitude          float64
postcode            object
price              float64
bedroom_number     float64
bathroom_number    float64
price_per_unit     float64
living_space       float64
land_space         float64
land_space_unit     object
property_type       object
dtype: object

In [45]:
# Convert 'acres' to square feet in the 'land_space' column
raw_data.loc[raw_data['land_space_unit'] == 'acres', 'land_space'] *= 43560.0

In [46]:
raw_data

,property_id,address,street_name,city,state,latitude,longitude,postcode,price,bedroom_number,bathroom_number,price_per_unit,living_space,land_space,land_space_unit,property_type
0,249518113,"117 3rd St, Wrangell, AK 99929",3rd St,Wrangell,AK,56.474518,-132.386000,99929,589500.0,3.0,3.0,237.0,2478.0,7492.000,sqft,SINGLE_FAMILY
1,249518139,"335 Cassiar St, Wrangell, AK 99929",Cassiar St,Wrangell,AK,56.475697,-132.389050,99929,405000.0,5.0,3.0,194.0,2080.0,10436.000,sqft,SINGLE_FAMILY
3,2069574197,"532.5 Front St, Wrangell, AK 99929",5 Front St,Wrangell,AK,56.468544,-132.379650,99929,130000.0,3.0,1.0,104.0,1250.0,3483.000,sqft,SINGLE_FAMILY
5,243013558,"501 Noseeum St, Petersburg, AK 99833",Noseeum St,Petersburg,AK,56.806820,-132.961800,99833,165000.0,1.0,1.0,235.0,700.0,15367.968,sqft,SINGLE_FAMILY
7,243013641,"905 Odin St, Petersburg, AK 99833",Odin St,Petersburg,AK,56.806230,-132.971130,99833,375000.0,3.0,3.0,226.0,1652.0,8000.000,sqft,SINGLE_FAMILY
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291229,4032186,"1026 Crestview Dr, Lemont, IL 60439",Crestview Dr,Lemont,IL,41.662193,-87.993800,60439,359990.0,3.0,2.0,196.0,1832.0,11900.592,sqft,SINGLE_FAMILY
291230,83909960,"611 Hickory Ln, West Chicago, IL 60185",Hickory Ln,West Chicago,IL,41.898396,-88.192670,60185,549000.0,4.0,5.0,161.0,3409.0,10890.000,sqft,SINGLE_FAMILY
291231,4303608,"6317 Virginia Ln, Matteson, IL 60443",Virginia Ln,Matteson,IL,41.523070,-87.769340,60443,350000.0,4.0,3.0,134.0,2600.0,10375.992,sqft,SINGLE_FAMILY
291232,65578365,"4701 Abbey Ln, Matteson, IL 60443",Abbey Ln,Matteson,IL,41.519527,-87.730644,60443,465000.0,5.0,4.0,140.0,3301.0,10193.040,sqft,SINGLE_FAMILY
291233,4418670,"321 Allen Ave, West Chicago, IL 60185",Allen Ave,West Chicago,IL,41.879490,-88.203010,60185,310000.0,4.0,2.0,181.0,1709.0,6634.188,sqft,SINGLE_FAMILY

In [47]:
# Update 'land_space_unit' to 'sqft' where 'acres' was converted
raw_data.loc[raw_data['land_space_unit'] == 'acres', 'land_space_unit'] = 'sqft'

In [48]:
raw_data

,property_id,address,street_name,city,state,latitude,longitude,postcode,price,bedroom_number,bathroom_number,price_per_unit,living_space,land_space,land_space_unit,property_type
0,249518113,"117 3rd St, Wrangell, AK 99929",3rd St,Wrangell,AK,56.474518,-132.386000,99929,589500.0,3.0,3.0,237.0,2478.0,7492.000,sqft,SINGLE_FAMILY
1,249518139,"335 Cassiar St, Wrangell, AK 99929",Cassiar St,Wrangell,AK,56.475697,-132.389050,99929,405000.0,5.0,3.0,194.0,2080.0,10436.000,sqft,SINGLE_FAMILY
3,2069574197,"532.5 Front St, Wrangell, AK 99929",5 Front St,Wrangell,AK,56.468544,-132.379650,99929,130000.0,3.0,1.0,104.0,1250.0,3483.000,sqft,SINGLE_FAMILY
5,243013558,"501 Noseeum St, Petersburg, AK 99833",Noseeum St,Petersburg,AK,56.806820,-132.961800,99833,165000.0,1.0,1.0,235.0,700.0,15367.968,sqft,SINGLE_FAMILY
7,243013641,"905 Odin St, Petersburg, AK 99833",Odin St,Petersburg,AK,56.806230,-132.971130,99833,375000.0,3.0,3.0,226.0,1652.0,8000.000,sqft,SINGLE_FAMILY
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291229,4032186,"1026 Crestview Dr, Lemont, IL 60439",Crestview Dr,Lemont,IL,41.662193,-87.993800,60439,359990.0,3.0,2.0,196.0,1832.0,11900.592,sqft,SINGLE_FAMILY
291230,83909960,"611 Hickory Ln, West Chicago, IL 60185",Hickory Ln,West Chicago,IL,41.898396,-88.192670,60185,549000.0,4.0,5.0,161.0,3409.0,10890.000,sqft,SINGLE_FAMILY
291231,4303608,"6317 Virginia Ln, Matteson, IL 60443",Virginia Ln,Matteson,IL,41.523070,-87.769340,60443,350000.0,4.0,3.0,134.0,2600.0,10375.992,sqft,SINGLE_FAMILY
291232,65578365,"4701 Abbey Ln, Matteson, IL 60443",Abbey Ln,Matteson,IL,41.519527,-87.730644,60443,465000.0,5.0,4.0,140.0,3301.0,10193.040,sqft,SINGLE_FAMILY
291233,4418670,"321 Allen Ave, West Chicago, IL 60185",Allen Ave,West Chicago,IL,41.879490,-88.203010,60185,310000.0,4.0,2.0,181.0,1709.0,6634.188,sqft,SINGLE_FAMILY

In [49]:
# Convert datatype object to string for 'postcode'
raw_data['postcode'] = raw_data['postcode'].astype(str)

In [50]:
# All numeric columns for which we want to identify outliers
numeric_columns = ['price', 'bedroom_number', 'bathroom_number', 'price_per_unit', 'living_space', 'land_space']

# Identify and count outliers for each numeric column
for column_name in numeric_columns:
    Q1 = raw_data[column_name].quantile(0.25)
    Q3 = raw_data[column_name].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = raw_data[(raw_data[column_name] < lower_bound) | (raw_data[column_name] > upper_bound)]

    num_outliers = outliers.shape[0]
    print(f"Number of outliers in {column_name}: {num_outliers}")

Number of outliers in price: 20789
Number of outliers in bedroom_number: 12317
Number of outliers in bathroom_number: 13647
Number of outliers in price_per_unit: 21825
Number of outliers in living_space: 10820
Number of outliers in land_space: 23982

In [51]:
# Dropping all rows with Outliers 
raw_data = raw_data.drop(outliers.index)

# Reset the index
raw_data = raw_data.reset_index(drop=True)

In [52]:
raw_data

,property_id,address,street_name,city,state,latitude,longitude,postcode,price,bedroom_number,bathroom_number,price_per_unit,living_space,land_space,land_space_unit,property_type
0,249518113,"117 3rd St, Wrangell, AK 99929",3rd St,Wrangell,AK,56.474518,-132.386000,99929,589500.0,3.0,3.0,237.0,2478.0,7492.000,sqft,SINGLE_FAMILY
1,249518139,"335 Cassiar St, Wrangell, AK 99929",Cassiar St,Wrangell,AK,56.475697,-132.389050,99929,405000.0,5.0,3.0,194.0,2080.0,10436.000,sqft,SINGLE_FAMILY
2,2069574197,"532.5 Front St, Wrangell, AK 99929",5 Front St,Wrangell,AK,56.468544,-132.379650,99929,130000.0,3.0,1.0,104.0,1250.0,3483.000,sqft,SINGLE_FAMILY
3,243013558,"501 Noseeum St, Petersburg, AK 99833",Noseeum St,Petersburg,AK,56.806820,-132.961800,99833,165000.0,1.0,1.0,235.0,700.0,15367.968,sqft,SINGLE_FAMILY
4,243013641,"905 Odin St, Petersburg, AK 99833",Odin St,Petersburg,AK,56.806230,-132.971130,99833,375000.0,3.0,3.0,226.0,1652.0,8000.000,sqft,SINGLE_FAMILY
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
248758,4032186,"1026 Crestview Dr, Lemont, IL 60439",Crestview Dr,Lemont,IL,41.662193,-87.993800,60439,359990.0,3.0,2.0,196.0,1832.0,11900.592,sqft,SINGLE_FAMILY
248759,83909960,"611 Hickory Ln, West Chicago, IL 60185",Hickory Ln,West Chicago,IL,41.898396,-88.192670,60185,549000.0,4.0,5.0,161.0,3409.0,10890.000,sqft,SINGLE_FAMILY
248760,4303608,"6317 Virginia Ln, Matteson, IL 60443",Virginia Ln,Matteson,IL,41.523070,-87.769340,60443,350000.0,4.0,3.0,134.0,2600.0,10375.992,sqft,SINGLE_FAMILY
248761,65578365,"4701 Abbey Ln, Matteson, IL 60443",Abbey Ln,Matteson,IL,41.519527,-87.730644,60443,465000.0,5.0,4.0,140.0,3301.0,10193.040,sqft,SINGLE_FAMILY
248762,4418670,"321 Allen Ave, West Chicago, IL 60185",Allen Ave,West Chicago,IL,41.879490,-88.203010,60185,310000.0,4.0,2.0,181.0,1709.0,6634.188,sqft,SINGLE_FAMILY

In [53]:
raw_data.to_csv("clean_data_outlier1.csv")

In [54]:
# Group the data by 'state' and count the unique property IDs
state_counts = raw_data.groupby('state')['property_id'].nunique()
state_counts

state
AK     1007
AR     3365
AZ    17575
BC       34
CA    50263
CO    11807
CT        1
HI     1857
IA      178
ID     4882
IL    16241
KS     6213
LA     6258
MO    12691
NE     4780
NM     3411
NV     8442
OK     7616
OR     8745
TX    61563
UT     6368
WA    14557
WY      909
Name: property_id, dtype: int64

In [55]:
# Select the top 5 states with the highest number of unique property IDs
top_states = state_counts.sort_values(ascending=False).head(5).index
top_states

Index(['TX', 'CA', 'AZ', 'IL', 'WA'], dtype='object', name='state')

In [58]:
# Shortlist the data for the top 5 states
top_states_data = raw_data[raw_data['state'].isin(top_states)]

# Reset the index
raw_data = raw_data.reset_index(drop=True)

# Display the shortlisted data
top_states_data.head(50)

,property_id,address,street_name,city,state,latitude,longitude,postcode,price,bedroom_number,bathroom_number,price_per_unit,living_space,land_space,land_space_unit,property_type
658,318990176,"649 Hargraves Avenue NE, Royal City, WA 99357",Hargraves Avenue NE,Royal City,WA,46.906307,-119.622284,99357,399900.0,4.0,3.0,229.0,1742.0,17193.132,sqft,SINGLE_FAMILY
674,2064111934,"3602 3602/3600 W 15th Ave, Kennewick, WA 99338",3602/3600 W 15th Ave,Kennewick,WA,46.194970,-119.192780,99338,389000.0,4.0,2.0,167.0,2328.0,15681.600,sqft,MULTI_FAMILY
675,331355531,"6087 W 34th Ave, Kennewick, WA 99338",W 34th Ave,Kennewick,WA,46.178677,-119.204510,99338,525000.0,4.0,3.0,220.0,2380.0,9583.000,sqft,SINGLE_FAMILY
676,85939771,"1506 S Olson St, Kennewick, WA 99338",S Olson St,Kennewick,WA,46.194546,-119.172320,99338,350000.0,3.0,2.0,228.0,1529.0,12632.400,sqft,SINGLE_FAMILY
677,85963207,"5907 W 14th Ave, Kennewick, WA 99338",W 14th Ave,Kennewick,WA,46.196050,-119.200966,99338,440000.0,3.0,2.0,268.0,1641.0,10454.400,sqft,SINGLE_FAMILY
678,251483237,"3787 S Sherman St, Kennewick, WA 99338",S Sherman St,Kennewick,WA,46.175232,-119.211670,99338,587900.0,3.0,2.0,252.0,2330.0,9147.600,sqft,SINGLE_FAMILY
679,204998627,"2206 S Kellogg Pl, Kennewick, WA 99338",S Kellogg Pl,Kennewick,WA,46.189290,-119.199990,99338,365000.0,3.0,2.0,259.0,1408.0,1408.000,sqft,SINGLE_FAMILY
680,331356014,"5665 W 32nd Ave, Kennewick, WA 99338",W 32nd Ave,Kennewick,WA,46.182080,-119.195755,99338,491900.0,4.0,2.0,274.0,1795.0,8276.400,sqft,SINGLE_FAMILY
681,204998611,"5718 W 23rd Ave, Kennewick, WA 99338",W 23rd Ave,Kennewick,WA,46.189632,-119.198660,99338,430000.0,3.0,3.0,203.0,2110.0,11761.200,sqft,SINGLE_FAMILY
682,2064292922,"6749 W 35th Ave, Kennewick, WA 99338",W 35th Ave,Kennewick,WA,46.177555,-119.201675,99338,639000.0,5.0,4.0,210.0,3029.0,11325.600,sqft,SINGLE_FAMILY
683,2064292956,"6869 W 38th Ave #109, Kennewick, WA 99338",W 38th Ave #109,Kennewick,WA,46.175117,-119.214010,99338,393000.0,2.0,2.0,287.0,1367.0,4174.000,sqft,SINGLE_FAMILY
684,2064292967,"6905 W 38th Ave #110, Kennewick, WA 99338",W 38th Ave #110,Kennewick,WA,46.173985,-119.203410,99338,393000.0,2.0,2.0,287.0,1367.0,3752.000,sqft,SINGLE_FAMILY
685,2064292974,"6917 W 38th Ave #111, Kennewick, WA 99338",W 38th Ave #111,Kennewick,WA,46.173985,-119.203410,99338,393000.0,2.0,2.0,287.0,1367.0,4356.000,sqft,SINGLE_FAMILY
686,126582595,"10295 W 18th Ct, Kennewick, WA 99338",W 18th Ct,Kennewick,WA,46.193770,-119.257710,99338,550000.0,5.0,4.0,224.0,2455.0,9147.600,sqft,SINGLE_FAMILY
687,331355778,"6994 W 31st Ave, Kennewick, WA 99338",W 31st Ave,Kennewick,WA,46.183212,-119.215940,99338,458000.0,3.0,2.0,285.0,1606.0,8889.000,sqft,SINGLE_FAMILY
688,311536379,"3737 S Taft St, Kennewick, WA 99338",S Taft St,Kennewick,WA,46.175950,-119.212250,99338,449900.0,3.0,2.0,304.0,1476.0,5227.200,sqft,SINGLE_FAMILY
689,251483216,"3064 S Dawes Pl, Kennewick, WA 99338",S Dawes Pl,Kennewick,WA,46.182358,-119.190750,99338,499900.0,4.0,3.0,228.0,2192.0,8712.000,sqft,SINGLE_FAMILY
691,205004322,"1883 S Fescue St, Kennewick, WA 99338",S Fescue St,Kennewick,WA,46.194023,-119.256350,99338,569000.0,4.0,3.0,214.0,2656.0,10018.800,sqft,SINGLE_FAMILY
693,2065530732,"7549 W 23rd Ave, Kennewick, WA 99338",W 23rd Ave,Kennewick,WA,46.189354,-119.191750,99338,910000.0,4.0,3.0,304.0,2986.0,14810.400,sqft,SINGLE_FAMILY
694,205039385,"3908 S McKinley St, Kennewick, WA 99338",S McKinley St,Kennewick,WA,46.174885,-119.204735,99338,525000.0,3.0,3.0,201.0,2608.0,9583.200,sqft,SINGLE_FAMILY
696,205012728,"3089 S Edison Ct, Kennewick, WA 99338",S Edison Ct,Kennewick,WA,46.183330,-119.193350,99338,580000.0,5.0,3.0,176.0,3278.0,9147.600,sqft,SINGLE_FAMILY
698,204996687,"6729 W 23rd Ave, Kennewick, WA 99338",W 23rd Ave,Kennewick,WA,46.187344,-119.212364,99338,789900.0,5.0,4.0,228.0,3457.0,13939.200,sqft,SINGLE_FAMILY
700,331356095,"5653 W 32nd Ave, Kennewick, WA 99338",W 32nd Ave,Kennewick,WA,46.182080,-119.195755,99338,453900.0,4.0,2.0,289.0,1566.0,8276.400,sqft,SINGLE_FAMILY
701,2065499165,"6917 W 35th Ave, Kennewick, WA 99338",W 35th Ave,Kennewick,WA,46.177555,-119.201675,99338,584103.0,3.0,3.0,252.0,2311.0,11325.600,sqft,SINGLE_FAMILY
703,85963596,"4931 W 24th Pl, Kennewick, WA 99338",W 24th Pl,Kennewick,WA,46.187057,-119.189064,99338,649900.0,4.0,4.0,242.0,2675.0,15398.460,sqft,SINGLE_FAMILY
704,205012803,"3933 S Kellogg St, Kennewick, WA 99338",S Kellogg St,Kennewick,WA,46.174503,-119.200630,99338,545000.0,3.0,3.0,261.0,2082.0,11761.200,sqft,SINGLE_FAMILY
705,2065564637,"3725 S Van Buren St #87, Kennewick, WA 99338",S Van Buren St #87,Kennewick,WA,46.181160,-119.213974,99338,473900.0,3.0,2.0,295.0,1602.0,7840.800,sqft,SINGLE_FAMILY
707,205039586,"10314 W 16th Pl, Kennewick, WA 99338",W 16th Pl,Kennewick,WA,46.196940,-119.259210,99338,449990.0,3.0,2.0,238.0,1885.0,9374.000,sqft,SINGLE_FAMILY
709,2065612817,"3781 S Van Buren St #83, Kennewick, WA 99338",S Van Buren St #83,Kennewick,WA,46.181160,-119.213974,99338,476130.0,3.0,2.0,297.0,1602.0,7840.800,sqft,SINGLE_FAMILY
711,205012802,"3893 S Kellogg St, Kennewick, WA 99338",S Kellogg St,Kennewick,WA,46.174793,-119.200560,99338,660000.0,3.0,2.0,236.0,2786.0,17859.600,sqft,SINGLE_FAMILY
729,251482812,"6930 W 31st Ave, Kennewick, WA 99338",W 31st Ave,Kennewick,WA,46.181904,-119.214700,99338,544000.0,3.0,2.0,264.0,2057.0,9583.200,sqft,SINGLE_FAMILY
730,2065616661,"7373 W 23rd Ave, Kennewick, WA 99338",W 23rd Ave,Kennewick,WA,46.189354,-119.191750,99338,879950.0,3.0,3.0,327.0,2689.0,12196.800,sqft,SINGLE_FAMILY
731,2066388970,"3682 S Van Buren St #100, Kennewick, WA 99338",S Van Buren St #100,Kennewick,WA,46.181160,-119.213974,99338,453000.0,3.0,2.0,302.0,1499.0,6758.000,sqft,SINGLE_FAMILY
732,2066390778,"3686 S Van Buren Pl #75, Kennewick, WA 99338",S Van Buren Pl #75,Kennewick,WA,46.195230,-119.214660,99338,453000.0,3.0,2.0,302.0,1499.0,6534.000,sqft,SINGLE_FAMILY
733,2066473891,"7319 W 23rd Ave, Kennewick, WA 99338",W 23rd Ave,Kennewick,WA,46.189354,-119.191750,99338,676850.0,3.0,2.0,321.0,2108.0,17545.968,sqft,SINGLE_FAMILY
734,331356176,"5659 W 32nd Ave, Kennewick, WA 99338",W 32nd Ave,Kennewick,WA,46.182080,-119.195755,99338,475900.0,4.0,2.0,278.0,1710.0,8276.400,sqft,SINGLE_FAMILY
735,331355861,"5635 W 32nd Ave, Kennewick, WA 99338",W 32nd Ave,Kennewick,WA,46.182080,-119.195755,99338,491900.0,4.0,2.0,274.0,1795.0,8712.000,sqft,SINGLE_FAMILY
736,2066843562,"6893 W 35th Ave, Kennewick, WA 99338",W 35th Ave,Kennewick,WA,46.177555,-119.201675,99338,554546.0,3.0,2.0,269.0,2057.0,11325.600,sqft,SINGLE_FAMILY
737,2066876853,"6965 W 38th Ave #115, Kennewick, WA 99338",W 38th Ave #115,Kennewick,WA,46.173985,-119.203410,99338,393000.0,2.0,2.0,287.0,1367.0,3956.000,sqft,SINGLE_FAMILY
738,2066876938,"6977 W 38th Ave #116, Kennewick, WA 99338",W 38th Ave #116,Kennewick,WA,46.173985,-119.203410,99338,393000.0,2.0,2.0,288.0,1363.0,3888.000,sqft,SINGLE_FAMILY
739,2066877556,"3770 S Van Buren Pl #81, Kennewick, WA 99338",S Van Buren Pl #81,Kennewick,WA,46.195230,-119.214660,99338,453000.0,3.0,3.0,304.0,1488.0,7010.000,sqft,SINGLE_FAMILY
740,2066877772,"3756 S Van Buren Pl #80, Kennewick, WA 99338",S Van Buren Pl #80,Kennewick,WA,46.195230,-119.214660,99338,453000.0,3.0,2.0,302.0,1499.0,6280.000,sqft,SINGLE_FAMILY
741,2066877895,"3742 S Van Buren Pl #79, Kennewick, WA 99338",S Van Buren Pl #79,Kennewick,WA,46.195230,-119.214660,99338,448000.0,3.0,2.0,299.0,1498.0,6288.000,sqft,SINGLE_FAMILY
742,2066878287,"3743 S Van Buren Pl #68, Kennewick, WA 99338",S Van Buren Pl #68,Kennewick,WA,46.195230,-119.214660,99338,518600.0,3.0,2.0,234.0,2215.0,9225.000,sqft,SINGLE_FAMILY
743,2067043236,"5777 W 28th Ave, Kennewick, WA 99338",W 28th Ave,Kennewick,WA,46.184235,-119.198900,99338,935000.0,5.0,3.0,252.0,3702.0,18295.200,sqft,SINGLE_FAMILY
744,2067062696,"6012 W 31st Ave, Kennewick, WA 99338",W 31st Ave,Kennewick,WA,46.182053,-119.198650,99338,549900.0,3.0,3.0,282.0,1948.0,14374.800,sqft,SINGLE_FAMILY
745,2067403276,"3715 S Van Buren Pl #70, Kennewick, WA 99338",S Van Buren Pl #70,Kennewick,WA,46.195230,-119.214660,99338,503000.0,4.0,2.0,267.0,1881.0,7405.200,sqft,SINGLE_FAMILY
746,2066881243,"3701 S Van Buren Pl #71, Kennewick, WA 99338",S Van Buren Pl #71,Kennewick,WA,46.195230,-119.214660,99338,455000.0,3.0,2.0,303.0,1499.0,7840.800,sqft,SINGLE_FAMILY
747,2067403729,"3728 S Van Buren Pl #78, Kennewick, WA 99338",S Van Buren Pl #78,Kennewick,WA,46.195230,-119.214660,99338,461462.0,3.0,2.0,307.0,1499.0,7840.800,sqft,SINGLE_FAMILY
748,2067404033,"3714 S Van Buren Pl #77, Kennewick, WA 99338",S Van Buren Pl #77,Kennewick,WA,46.195230,-119.214660,99338,473900.0,3.0,2.0,295.0,1602.0,7840.800,sqft,SINGLE_FAMILY