# Data Cleaning and Splitting

In [1]:
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
import numpy as np

In [2]:
raw_data = pd.read_csv("600K US Housing Properties.csv")
raw_data.head()

C:\Users\supre\AppData\Local\Temp\ipykernel_268\4237909321.py:1: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  raw_data = pd.read_csv("600K US Housing Properties.csv")

,property_url,property_id,address,street_name,apartment,city,state,latitude,longitude,postcode,...,property_type,property_status,year_build,total_num_units,listing_age,RunDate,agency_name,agent_name,agent_phone,is_owned_by_zillow
0,https://www.zillow.com/homedetails/3-Plat-83-1...,2064212272,"3 Plat #83-10, Wrangell, AK 99929",Plat #83-10,NaN,Wrangell,AK,NaN,NaN,99929,...,LOT,FOR_SALE,NaN,NaN,-1,2022-04-24 07:34:15,Anchor Properties,NaN,NaN,0
1,https://www.zillow.com/homedetails/117-3rd-St-...,249518113,"117 3rd St, Wrangell, AK 99929",3rd St,NaN,Wrangell,AK,56.474518,-132.38600,99929,...,SINGLE_FAMILY,FOR_SALE,NaN,NaN,-1,2022-04-24 07:34:15,NaN,NaN,NaN,0
2,https://www.zillow.com/homedetails/LOT-2A-Fron...,2077729913,"LOT 2A Front St, Wrangell, AK 99929",LOT 2A Front St,NaN,Wrangell,AK,56.471638,-132.38686,99929,...,LOT,FOR_SALE,NaN,NaN,-1,2022-04-24 07:34:15,NaN,NaN,NaN,0
3,https://www.zillow.com/homedetails/LOT-A-Plat-...,2067488502,"LOT A Plat #2009-6, Wrangell, AK 99929",LOT A Plat #2009-6,NaN,Wrangell,AK,NaN,NaN,99929,...,SINGLE_FAMILY,FOR_SALE,NaN,NaN,-1,2022-04-24 07:34:15,"Petersburg Properties, LLC",NaN,NaN,0
4,https://www.zillow.com/homedetails/335-Cassiar...,249518139,"335 Cassiar St, Wrangell, AK 99929",Cassiar St,NaN,Wrangell,AK,56.475697,-132.38905,99929,...,SINGLE_FAMILY,FOR_SALE,NaN,NaN,-1,2022-04-24 07:34:15,NaN,NaN,NaN,0

In [3]:
# Selecting usefull Columns and Dropping others
raw_data = raw_data[['property_id','address','street_name','city','state','latitude','longitude','postcode'
            ,'price','bedroom_number','bathroom_number','price_per_unit','living_space','land_space','land_space_unit'
            ,'property_type']]

In [4]:
raw_data

,property_id,address,street_name,city,state,latitude,longitude,postcode,price,bedroom_number,bathroom_number,price_per_unit,living_space,land_space,land_space_unit,property_type
0,2064212272,"3 Plat #83-10, Wrangell, AK 99929",Plat #83-10,Wrangell,AK,NaN,NaN,99929,135000.0,NaN,NaN,NaN,NaN,3.8860,acres,LOT
1,249518113,"117 3rd St, Wrangell, AK 99929",3rd St,Wrangell,AK,56.474518,-132.386000,99929,589500.0,3.0,3.0,237.0,2478.0,7492.0000,sqft,SINGLE_FAMILY
2,2077729913,"LOT 2A Front St, Wrangell, AK 99929",LOT 2A Front St,Wrangell,AK,56.471638,-132.386860,99929,99999.0,NaN,0.0,NaN,NaN,7222.0000,sqft,LOT
3,2067488502,"LOT A Plat #2009-6, Wrangell, AK 99929",LOT A Plat #2009-6,Wrangell,AK,NaN,NaN,99929,495000.0,3.0,1.0,330.0,1500.0,61.9705,acres,SINGLE_FAMILY
4,249518139,"335 Cassiar St, Wrangell, AK 99929",Cassiar St,Wrangell,AK,56.475697,-132.389050,99929,405000.0,5.0,3.0,194.0,2080.0,10436.0000,sqft,SINGLE_FAMILY
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599995,4303608,"6317 Virginia Ln, Matteson, IL 60443",Virginia Ln,Matteson,IL,41.523070,-87.769340,60443,350000.0,4.0,3.0,134.0,2600.0,10375.9920,sqft,SINGLE_FAMILY
599996,2078144422,"LOT 16 Ray Ave, West Chicago, IL 60185",LOT 16 Ray Ave,West Chicago,IL,NaN,NaN,60185,29900.0,NaN,NaN,NaN,NaN,0.2600,acres,LOT
599997,4604875,"12S135 Lemont Rd, Lemont, IL 60439",135 Lemont Rd,Lemont,IL,41.697723,-88.003746,60439,859000.0,3.0,3.0,254.0,3373.0,4.8204,acres,SINGLE_FAMILY
599998,65578365,"4701 Abbey Ln, Matteson, IL 60443",Abbey Ln,Matteson,IL,41.519527,-87.730644,60443,465000.0,5.0,4.0,140.0,3301.0,10193.0400,sqft,SINGLE_FAMILY
599999,4418670,"321 Allen Ave, West Chicago, IL 60185",Allen Ave,West Chicago,IL,41.879490,-88.203010,60185,310000.0,4.0,2.0,181.0,1709.0,6634.1880,sqft,SINGLE_FAMILY

In [5]:
raw_data.isnull().sum()

property_id             0
address                 0
street_name           131
city                    1
state                   1
latitude            70878
longitude           70878
postcode               30
price                   0
bedroom_number     156155
bathroom_number    128267
price_per_unit     164635
living_space       152153
land_space          84881
land_space_unit     84881
property_type           0
dtype: int64

In [6]:
raw_data.dropna(subset=['price_per_unit'], inplace=True)

In [7]:
raw_data.isnull().sum()

property_id            0
address                0
street_name           10
city                   1
state                  0
latitude           28314
longitude          28314
postcode               5
price                  0
bedroom_number      5206
bathroom_number     3119
price_per_unit         0
living_space           0
land_space         76491
land_space_unit    76491
property_type          0
dtype: int64

In [8]:
raw_data.dropna(subset=['land_space'], inplace=True)

In [9]:
raw_data.isnull().sum()

property_id            0
address                0
street_name            4
city                   1
state                  0
latitude           23135
longitude          23135
postcode               5
price                  0
bedroom_number      4809
bathroom_number     2875
price_per_unit         0
living_space           0
land_space             0
land_space_unit        0
property_type          0
dtype: int64

In [10]:
raw_data.dropna(subset=['bedroom_number'], inplace=True)

In [11]:
raw_data.dropna(subset=['bathroom_number'], inplace=True)

In [12]:
raw_data.dropna(subset=['latitude'], inplace=True)

In [13]:
raw_data.dropna(subset=['longitude'], inplace=True)

In [14]:
raw_data.dropna(subset=['street_name'], inplace=True)

In [15]:
raw_data.dropna(subset=['city'], inplace=True)

In [16]:
raw_data.isnull().sum()

property_id        0
address            0
street_name        0
city               0
state              0
latitude           0
longitude          0
postcode           3
price              0
bedroom_number     0
bathroom_number    0
price_per_unit     0
living_space       0
land_space         0
land_space_unit    0
property_type      0
dtype: int64

In [17]:
raw_data.dropna(subset=['postcode'], inplace=True)

In [18]:
raw_data.dtypes

property_id          int64
address             object
street_name         object
city                object
state               object
latitude           float64
longitude          float64
postcode            object
price              float64
bedroom_number     float64
bathroom_number    float64
price_per_unit     float64
living_space       float64
land_space         float64
land_space_unit     object
property_type       object
dtype: object

In [19]:
# Convert 'acres' to square feet in the 'land_space' column
raw_data.loc[raw_data['land_space_unit'] == 'acres', 'land_space'] *= 43560.0

In [20]:
# Update 'land_space_unit' to 'sqft' where 'acres' was converted
raw_data.loc[raw_data['land_space_unit'] == 'acres', 'land_space_unit'] = 'sqft'

In [21]:
# Dropping rows where 'state' equal to 'BC'
raw_data = raw_data[raw_data['state'] != 'BC']

In [22]:
raw_data = raw_data[raw_data['bedroom_number'] <= 5]

In [23]:
# Dropping rows where 'bathroom_number' equal to '0' and more than 10
raw_data = raw_data[(raw_data['bathroom_number'] <= 8) & (raw_data['bathroom_number'] >= 1)]

In [24]:
raw_data = raw_data[(raw_data['living_space'] <= 10000) & (raw_data['living_space'] >= 400)]

In [25]:
# Convert datatype object to string for 'postcode'
raw_data['postcode'] = raw_data['postcode'].astype(str)

In [26]:
raw_data.shape

(318646, 16)

In [27]:
# All numeric columns for which we want to identify outliers
numeric_columns = ['price', 'bedroom_number', 'bathroom_number', 'living_space', 'land_space']

# Identify and count outliers for each numeric column
for column_name in numeric_columns:
    Q1 = raw_data[column_name].quantile(0.25)
    Q3 = raw_data[column_name].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = raw_data[(raw_data[column_name] < lower_bound) | (raw_data[column_name] > upper_bound)]

    num_outliers = outliers.shape[0]
    print(f"Number of outliers in {column_name}: {num_outliers}")

Number of outliers in price: 24270
Number of outliers in bedroom_number: 6644
Number of outliers in bathroom_number: 13369
Number of outliers in living_space: 12456
Number of outliers in land_space: 55551

In [28]:
# Dropping all rows with Outliers 
raw_data = raw_data.drop(outliers.index)

# Reset the index
raw_data = raw_data.reset_index(drop=True)

In [29]:
raw_data.shape

(263095, 16)

In [30]:
raw_data.to_csv("clean_data_outlier.csv")

In [31]:
# Group the data by 'state' and count the unique property IDs
state_counts = raw_data.groupby('state')['property_id'].nunique()
state_counts

state
AK     1118
AR     4179
AZ    18167
CA    51735
CO    12041
CT        1
HI     1949
IA      177
ID     5086
IL    17256
KS     6646
LA     7224
MO    13931
NE     4889
NM     3807
NV     8905
OK     8569
OR     9159
TX    65780
UT     6256
WA    15255
WY      965
Name: property_id, dtype: int64

In [32]:
# Select the top 5 states with the highest number of unique property IDs
top_states = state_counts.sort_values(ascending=False).head(5).index
top_states

Index(['TX', 'CA', 'AZ', 'IL', 'WA'], dtype='object', name='state')

In [33]:
# Shortlist the data for the top 5 states
top_states_data = raw_data[raw_data['state'].isin(top_states)]

# Reset the index
top_states_data = top_states_data.reset_index(drop=True)

# Display the shortlisted data
top_states_data.head(50)

,property_id,address,street_name,city,state,latitude,longitude,postcode,price,bedroom_number,bathroom_number,price_per_unit,living_space,land_space,land_space_unit,property_type
0,318990176,"649 Hargraves Avenue NE, Royal City, WA 99357",Hargraves Avenue NE,Royal City,WA,46.906307,-119.622284,99357,399900.0,4.0,3.0,229.0,1742.0,17193.132,sqft,SINGLE_FAMILY
1,204997510,"15822 S Clear View Loop, Kennewick, WA 99338",S Clear View Loop,Kennewick,WA,46.190080,-119.318460,99338,799000.0,4.0,3.0,306.0,2611.0,26893.944,sqft,SINGLE_FAMILY
2,2064111934,"3602 3602/3600 W 15th Ave, Kennewick, WA 99338",3602/3600 W 15th Ave,Kennewick,WA,46.194970,-119.192780,99338,389000.0,4.0,2.0,167.0,2328.0,15681.600,sqft,MULTI_FAMILY
3,331355531,"6087 W 34th Ave, Kennewick, WA 99338",W 34th Ave,Kennewick,WA,46.178677,-119.204510,99338,525000.0,4.0,3.0,220.0,2380.0,9583.000,sqft,SINGLE_FAMILY
4,85939771,"1506 S Olson St, Kennewick, WA 99338",S Olson St,Kennewick,WA,46.194546,-119.172320,99338,350000.0,3.0,2.0,228.0,1529.0,12632.400,sqft,SINGLE_FAMILY
5,204997385,"13308 S Grandview Ln, Kennewick, WA 99338",S Grandview Ln,Kennewick,WA,46.192604,-119.326720,99338,799900.0,3.0,3.0,294.0,2712.0,23857.812,sqft,SINGLE_FAMILY
6,126582680,"17640 S Fairview Loop, Kennewick, WA 99338",S Fairview Loop,Kennewick,WA,46.188590,-119.312620,99338,639900.0,4.0,3.0,277.0,2308.0,24110.460,sqft,SINGLE_FAMILY
7,85963207,"5907 W 14th Ave, Kennewick, WA 99338",W 14th Ave,Kennewick,WA,46.196050,-119.200966,99338,440000.0,3.0,2.0,268.0,1641.0,10454.400,sqft,SINGLE_FAMILY
8,85947076,"294 Rachel Rd, Kennewick, WA 99338",Rachel Rd,Kennewick,WA,46.209940,-119.283450,99338,629900.0,4.0,3.0,265.0,2373.0,21780.000,sqft,SINGLE_FAMILY
9,251483237,"3787 S Sherman St, Kennewick, WA 99338",S Sherman St,Kennewick,WA,46.175232,-119.211670,99338,587900.0,3.0,2.0,252.0,2330.0,9147.600,sqft,SINGLE_FAMILY
10,204998627,"2206 S Kellogg Pl, Kennewick, WA 99338",S Kellogg Pl,Kennewick,WA,46.189290,-119.199990,99338,365000.0,3.0,2.0,259.0,1408.0,1408.000,sqft,SINGLE_FAMILY
11,331356014,"5665 W 32nd Ave, Kennewick, WA 99338",W 32nd Ave,Kennewick,WA,46.182080,-119.195755,99338,491900.0,4.0,2.0,274.0,1795.0,8276.400,sqft,SINGLE_FAMILY
12,204998611,"5718 W 23rd Ave, Kennewick, WA 99338",W 23rd Ave,Kennewick,WA,46.189632,-119.198660,99338,430000.0,3.0,3.0,203.0,2110.0,11761.200,sqft,SINGLE_FAMILY
13,2064292922,"6749 W 35th Ave, Kennewick, WA 99338",W 35th Ave,Kennewick,WA,46.177555,-119.201675,99338,639000.0,5.0,4.0,210.0,3029.0,11325.600,sqft,SINGLE_FAMILY
14,2064292956,"6869 W 38th Ave #109, Kennewick, WA 99338",W 38th Ave #109,Kennewick,WA,46.175117,-119.214010,99338,393000.0,2.0,2.0,287.0,1367.0,4174.000,sqft,SINGLE_FAMILY
15,2064292967,"6905 W 38th Ave #110, Kennewick, WA 99338",W 38th Ave #110,Kennewick,WA,46.173985,-119.203410,99338,393000.0,2.0,2.0,287.0,1367.0,3752.000,sqft,SINGLE_FAMILY
16,2064292974,"6917 W 38th Ave #111, Kennewick, WA 99338",W 38th Ave #111,Kennewick,WA,46.173985,-119.203410,99338,393000.0,2.0,2.0,287.0,1367.0,4356.000,sqft,SINGLE_FAMILY
17,126582595,"10295 W 18th Ct, Kennewick, WA 99338",W 18th Ct,Kennewick,WA,46.193770,-119.257710,99338,550000.0,5.0,4.0,224.0,2455.0,9147.600,sqft,SINGLE_FAMILY
18,331355778,"6994 W 31st Ave, Kennewick, WA 99338",W 31st Ave,Kennewick,WA,46.183212,-119.215940,99338,458000.0,3.0,2.0,285.0,1606.0,8889.000,sqft,SINGLE_FAMILY
19,311536379,"3737 S Taft St, Kennewick, WA 99338",S Taft St,Kennewick,WA,46.175950,-119.212250,99338,449900.0,3.0,2.0,304.0,1476.0,5227.200,sqft,SINGLE_FAMILY
20,251483216,"3064 S Dawes Pl, Kennewick, WA 99338",S Dawes Pl,Kennewick,WA,46.182358,-119.190750,99338,499900.0,4.0,3.0,228.0,2192.0,8712.000,sqft,SINGLE_FAMILY
21,205004322,"1883 S Fescue St, Kennewick, WA 99338",S Fescue St,Kennewick,WA,46.194023,-119.256350,99338,569000.0,4.0,3.0,214.0,2656.0,10018.800,sqft,SINGLE_FAMILY
22,2065530732,"7549 W 23rd Ave, Kennewick, WA 99338",W 23rd Ave,Kennewick,WA,46.189354,-119.191750,99338,910000.0,4.0,3.0,304.0,2986.0,14810.400,sqft,SINGLE_FAMILY
23,205039385,"3908 S McKinley St, Kennewick, WA 99338",S McKinley St,Kennewick,WA,46.174885,-119.204735,99338,525000.0,3.0,3.0,201.0,2608.0,9583.200,sqft,SINGLE_FAMILY
24,205012728,"3089 S Edison Ct, Kennewick, WA 99338",S Edison Ct,Kennewick,WA,46.183330,-119.193350,99338,580000.0,5.0,3.0,176.0,3278.0,9147.600,sqft,SINGLE_FAMILY
25,204996687,"6729 W 23rd Ave, Kennewick, WA 99338",W 23rd Ave,Kennewick,WA,46.187344,-119.212364,99338,789900.0,5.0,4.0,228.0,3457.0,13939.200,sqft,SINGLE_FAMILY
26,331356095,"5653 W 32nd Ave, Kennewick, WA 99338",W 32nd Ave,Kennewick,WA,46.182080,-119.195755,99338,453900.0,4.0,2.0,289.0,1566.0,8276.400,sqft,SINGLE_FAMILY
27,2065499165,"6917 W 35th Ave, Kennewick, WA 99338",W 35th Ave,Kennewick,WA,46.177555,-119.201675,99338,584103.0,3.0,3.0,252.0,2311.0,11325.600,sqft,SINGLE_FAMILY
28,85963596,"4931 W 24th Pl, Kennewick, WA 99338",W 24th Pl,Kennewick,WA,46.187057,-119.189064,99338,649900.0,4.0,4.0,242.0,2675.0,15398.460,sqft,SINGLE_FAMILY
29,205012803,"3933 S Kellogg St, Kennewick, WA 99338",S Kellogg St,Kennewick,WA,46.174503,-119.200630,99338,545000.0,3.0,3.0,261.0,2082.0,11761.200,sqft,SINGLE_FAMILY
30,2065564637,"3725 S Van Buren St #87, Kennewick, WA 99338",S Van Buren St #87,Kennewick,WA,46.181160,-119.213974,99338,473900.0,3.0,2.0,295.0,1602.0,7840.800,sqft,SINGLE_FAMILY
31,205039586,"10314 W 16th Pl, Kennewick, WA 99338",W 16th Pl,Kennewick,WA,46.196940,-119.259210,99338,449990.0,3.0,2.0,238.0,1885.0,9374.000,sqft,SINGLE_FAMILY
32,2065612817,"3781 S Van Buren St #83, Kennewick, WA 99338",S Van Buren St #83,Kennewick,WA,46.181160,-119.213974,99338,476130.0,3.0,2.0,297.0,1602.0,7840.800,sqft,SINGLE_FAMILY
33,205012802,"3893 S Kellogg St, Kennewick, WA 99338",S Kellogg St,Kennewick,WA,46.174793,-119.200560,99338,660000.0,3.0,2.0,236.0,2786.0,17859.600,sqft,SINGLE_FAMILY
34,120149140,"2936 Lorayne J Blvd, Kennewick, WA 99338",Lorayne J Blvd,Kennewick,WA,46.205746,-119.269745,99338,575000.0,5.0,3.0,201.0,2860.0,22215.600,sqft,SINGLE_FAMILY
35,251482812,"6930 W 31st Ave, Kennewick, WA 99338",W 31st Ave,Kennewick,WA,46.181904,-119.214700,99338,544000.0,3.0,2.0,264.0,2057.0,9583.200,sqft,SINGLE_FAMILY
36,2065616661,"7373 W 23rd Ave, Kennewick, WA 99338",W 23rd Ave,Kennewick,WA,46.189354,-119.191750,99338,879950.0,3.0,3.0,327.0,2689.0,12196.800,sqft,SINGLE_FAMILY
37,2066388970,"3682 S Van Buren St #100, Kennewick, WA 99338",S Van Buren St #100,Kennewick,WA,46.181160,-119.213974,99338,453000.0,3.0,2.0,302.0,1499.0,6758.000,sqft,SINGLE_FAMILY
38,2066390778,"3686 S Van Buren Pl #75, Kennewick, WA 99338",S Van Buren Pl #75,Kennewick,WA,46.195230,-119.214660,99338,453000.0,3.0,2.0,302.0,1499.0,6534.000,sqft,SINGLE_FAMILY
39,2066473891,"7319 W 23rd Ave, Kennewick, WA 99338",W 23rd Ave,Kennewick,WA,46.189354,-119.191750,99338,676850.0,3.0,2.0,321.0,2108.0,17545.968,sqft,SINGLE_FAMILY
40,331356176,"5659 W 32nd Ave, Kennewick, WA 99338",W 32nd Ave,Kennewick,WA,46.182080,-119.195755,99338,475900.0,4.0,2.0,278.0,1710.0,8276.400,sqft,SINGLE_FAMILY
41,331355861,"5635 W 32nd Ave, Kennewick, WA 99338",W 32nd Ave,Kennewick,WA,46.182080,-119.195755,99338,491900.0,4.0,2.0,274.0,1795.0,8712.000,sqft,SINGLE_FAMILY
42,2066843562,"6893 W 35th Ave, Kennewick, WA 99338",W 35th Ave,Kennewick,WA,46.177555,-119.201675,99338,554546.0,3.0,2.0,269.0,2057.0,11325.600,sqft,SINGLE_FAMILY
43,2066876853,"6965 W 38th Ave #115, Kennewick, WA 99338",W 38th Ave #115,Kennewick,WA,46.173985,-119.203410,99338,393000.0,2.0,2.0,287.0,1367.0,3956.000,sqft,SINGLE_FAMILY
44,2066876938,"6977 W 38th Ave #116, Kennewick, WA 99338",W 38th Ave #116,Kennewick,WA,46.173985,-119.203410,99338,393000.0,2.0,2.0,288.0,1363.0,3888.000,sqft,SINGLE_FAMILY
45,2066877556,"3770 S Van Buren Pl #81, Kennewick, WA 99338",S Van Buren Pl #81,Kennewick,WA,46.195230,-119.214660,99338,453000.0,3.0,3.0,304.0,1488.0,7010.000,sqft,SINGLE_FAMILY
46,2066877772,"3756 S Van Buren Pl #80, Kennewick, WA 99338",S Van Buren Pl #80,Kennewick,WA,46.195230,-119.214660,99338,453000.0,3.0,2.0,302.0,1499.0,6280.000,sqft,SINGLE_FAMILY
47,2066877895,"3742 S Van Buren Pl #79, Kennewick, WA 99338",S Van Buren Pl #79,Kennewick,WA,46.195230,-119.214660,99338,448000.0,3.0,2.0,299.0,1498.0,6288.000,sqft,SINGLE_FAMILY
48,2066878287,"3743 S Van Buren Pl #68, Kennewick, WA 99338",S Van Buren Pl #68,Kennewick,WA,46.195230,-119.214660,99338,518600.0,3.0,2.0,234.0,2215.0,9225.000,sqft,SINGLE_FAMILY
49,2067043236,"5777 W 28th Ave, Kennewick, WA 99338",W 28th Ave,Kennewick,WA,46.184235,-119.198900,99338,935000.0,5.0,3.0,252.0,3702.0,18295.200,sqft,SINGLE_FAMILY

In [34]:
top_states_data.to_csv("clean_data_outlier1.csv")

In [35]:
texas_data = state_counts.sort_values(ascending=False).head(1).index

In [36]:
texas_state_data = raw_data[raw_data['state'].isin(texas_data)]

# Reset the index
texas_state_data = texas_state_data.reset_index(drop=True)

# Display the shortlisted data
texas_state_data.head()

,property_id,address,street_name,city,state,latitude,longitude,postcode,price,bedroom_number,bathroom_number,price_per_unit,living_space,land_space,land_space_unit,property_type
0,27399441,"1116 Saint Johns Dr, El Paso, TX 79903",Saint Johns Dr,El Paso,TX,31.786737,-106.42802,79903,239500.0,5.0,3.0,141.0,1692.0,6969.6,sqft,SINGLE_FAMILY
1,27498318,"1101 Apache St, El Paso, TX 79925",Apache St,El Paso,TX,31.784021,-106.40445,79925,165000.0,4.0,2.0,100.0,1650.0,12632.4,sqft,SINGLE_FAMILY
2,27497333,"452 Val Verde St, El Paso, TX 79905",Val Verde St,El Paso,TX,31.761911,-106.43233,79905,118000.0,4.0,1.0,61.0,1918.0,11325.6,sqft,SINGLE_FAMILY
3,27416021,"4600 Cumberland Cir, El Paso, TX 79903",Cumberland Cir,El Paso,TX,31.790165,-106.43596,79903,414700.0,4.0,3.0,132.0,3119.0,15246.0,sqft,SINGLE_FAMILY
4,27397349,"6028 Aztec Rd, El Paso, TX 79925",Aztec Rd,El Paso,TX,31.785316,-106.41115,79925,174950.0,4.0,2.0,97.0,1800.0,6098.4,sqft,SINGLE_FAMILY

In [37]:
texas_state_data.shape

(65780, 16)

In [38]:
texas_state_data.to_csv("texas_state_data.csv")